version: "3.7"
services:
  # ====================================================================================================================
  # POSTGRES SERVER
  # ====================================================================================================================
  pg-docker:
    image: postgres:14-alpine
    container_name: dev-postgresql
    environment:
      POSTGRES_DB: dslist
      POSTGRES_PASSWORD: 1234567
    ports:
      - 5434:5432
    volumes:
      - ./.data/postgresql/data:/var/lib/postgresql/data
      - ./create.sql:/docker-entrypoint-initdb.d/create.sql
    networks:
      - dev-network
  # ====================================================================================================================
  # Spring Boot Application
  # ====================================================================================================================
  dslist-docker:
    build: .
    container_name: dev-dslist
    ports:
      - 8080:8080
    environment:
      db-url: jdbc:postgresql://pg-docker:5432/dslist
      db-username: postgres
      db-password: 1234567
    depends_on:
      - pg-docker
    networks:
      - dev-network
  # ====================================================================================================================
  # PGADMIN
  # ====================================================================================================================
  # pgadmin-docker:
  #   image: dpage/pgadmin4
  #   container_name: dev-pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: me@example.com
  #     PGADMIN_DEFAULT_PASSWORD: 1234567
  #   ports:
  #     - 5050:80
  #   volumes:
  #     - ./.data/pgadmin:/var/lib/pgadmin
  #   depends_on:
  #     - pg-docker
  #   networks:
  #     - dev-network
# ======================================================================================================================
# REDE
# ======================================================================================================================
networks:
  dev-network:
    driver: bridge